# Generated by Django 4.0.4 on 2022-06-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astroPics_rest_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomypicture',
            name='explanation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='astronomypicture',
            name='hdurl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='astronomypicture',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
